### ISSUE TITLE
[Тут кількома словами опишіть проблему]

### ISSUE THREAD

**Issue by Churik6000** [yanchukcha/deltarune-ua#12]
**Опис**
При запуску гри після заміни тек lang і data у грі стається помилка, яка просто не дає можливості запустити гру

**Виявлення помилки**
Щойно я  загружаю все і нажимаю будь-що після появи надпису deltarune

**Поведінка**

**Знімки екрана**
![image](https://github.com/yanchukcha/deltarune-ua/assets/140672592/ed532a45-be57-4d6a-a8e0-8ac4a9f32b4a)

**Пристрій (будь ласка, заповніть наступну інформацію):**
 Windows

**Додатково**

**Comment by DanielleTlumach** [comment]
А ви правильно робите заміну файлів?
Якщо оновлюєте переклад - видаліть з lang оригінальні файли з перекладом англійською та японською та стару теку ua.

**Comment by DanielleTlumach** [comment]
Спробувала відтворили помилку... Дуже дивно... У мене все працює

**Comment by DanielleTlumach** [comment]
Ви точно правильно замінили файли?

**Comment by DanielleTlumach** [comment]
Цей... спробуй нову версію - 0.2.1

**Comment by Churik6000** [comment]
Ура, з версією 0.2.1 усе працює
