### ISSUE TITLE
[Тут кількома словами опишіть проблему]

### ISSUE THREAD

**Issue by utf64** [yanchukcha/deltarune-ua#14]
**Опис**
Я отримую помилку chapter select error коли запускаю гру

**Виявлення помилки**

1. Пройдіть 2 розділи.
2. Натисніть на кнопку стерти в обох розділах.
3. Перезапумтіть гру.
4. Гляньте на помилку.

**Пристрій**
 - О.С: Android
 - Браузер: Chrome
 - Версія О.С: Android 10
 - Версія перекладу: 0.2.2

**Додатково**
Гру неможливо запустити.
Граю на простій версії
не shaderless.

**Comment by DanielleTlumach** [comment]
Виправили. В наступному оновленні такого не буде.
