### ISSUE TITLE
Неправильні настанови для встановлення під Лінуксом.

### ISSUE THREAD

**Issue by DxPCbrake** [yanchukcha/deltarune-ua#18]
В Лінуксверсії немає теки "assets", треба просто викласти вміст архіву в корінь теки гри. Плюс в архіві лежить файл "game.unx", який треба самому перейменувати на "data.win", але в описі встановлення цього не зазначено.

Прохання.
Допрацюйте гайд для встановлення під Лінукс, плюс, можна було б щей й перейменувати в архіві "game.unx" на "data.win"

Версія гри: 1.10
Версія локалізації: v0.2.3

**Comment by DanielleTlumach** [comment]
Добридень!
Дякуємо за зауваження, в наступному оновленні локалізація буде повністю справна на ОС Linux.

**Comment by DxPCbrake** [comment]
Доброго.
Та це я Вам дякую, за локалізацію. Вже почав грати.

**Comment by DanielleTlumach** [comment]
Доброї ночі!
З виходом чергового оновлення нашої локалізації в блоці про встановлення зробили примітки для користувачів Linux, що запускають Windows ігри на Proton'і та без нього.
