### ISSUE TITLE
Неправильний переклад терміну "tomboy"

### ISSUE THREAD

**Issue by YevhenLaiba** [yanchukcha/deltarune-ua#19]
**Опис**
Помилка перекладу - терміни "tomboyish" та "tomboy" перекладено як "парубійський" або "хлопчисько". Термін використано в частині з будуваням Задодерної Машини у Розділі 1 описуючи "башку" "МЕЧ" та тіло "Колесо". Це точно відноситься до Сьюзи, бо вона багато разів у грі описана як "лиха дівчина" та якщо обрати башку "МЕЧ", копія машини, зроблена зі сміття Лансером та Сьюзі матиме голову з перукою, схожою на волосся Сьюзі.
![hqdefault](https://github.com/user-attachments/assets/f1bd7406-c3e1-4ec0-93bb-0d18a0d04d48)
Перекласти можна як "пацанка" (пацанковий), "хлопчур" (хлопчурський) або ж просто "томбой" (томбойський).

**Виявлення помилки**
1. Перейдіть до «strings_ch1.json»
2. Знайдіть рядок 2271 «"obj_thrashcontroller_slash_Create_0_gml_89_0"» та «"obj_thrashcontroller_slash_Create_0_gml_89_0"»
3. Гляньте на помилку.

Інш.
1. Перейдіть до «Розділ 1 "Початок"»
2. Дійдіть до «сеґменту з будуваням "Задодерної машини"»
3. Оберіть "башку" «МЕЧ» та тіло «КОЛЕСО»
4. Прочитайте опис
5. Помилку знайдено.

**Знімки екрана**
У оригінальній, англійській, версії
![Знімок екрана 2024-11-03 031154](https://github.com/user-attachments/assets/bfe8e49e-ecd4-4c79-b5e8-5c5c3de66d93)
![Знімок екрана 2024-11-03 031206](https://github.com/user-attachments/assets/9943092f-fa02-4008-9977-dee80a0381ac)
У локалізації
![Знімок екрана 2024-11-03 031248](https://github.com/user-attachments/assets/f0d6aeaf-6cd7-4433-8f39-5b71ea6ed4b4)
![Знімок екрана 2024-11-03 034108](https://github.com/user-attachments/assets/13a58add-fe20-4479-a0c1-ab7a4625e041)

**Пристрій**
 - О.С: Windows
 - Браузер: Firefox
 - Версія О.С: Windows 11
 - Версія перекладу: v0.2.4
 - Версія гри: v1.10

**Comment by DanielleTlumach** [comment]
Доброї ночі!
Незабаром розглянемо це.

**Comment by DanielleTlumach** [comment]
Доброго вечора!
Після довгих обговорень між перекладачами нашої команди, ми вирішили замінити в локалізації назву того леза з “парубійського” на “пацаняче”.
