### ISSUE TITLE
[Помилка]

### ISSUE THREAD

**Issue by sawer097** [yanchukcha/deltarune-ua#4]
[**Опишіть]) проблему**
Якомога читкіше опишіть свою проблему (Напр. Це помилка перекладу чи баґ, та як її/його можна виявити)

**Виявлення помилки**
Покрокове пояснення, як нам виявити помилку:
1. Перейдіть до 'Після воз'єднання кріса ноель та с'юзі і ральзей всі вони піднімаються по сходах і коли починаються салюти які можуть ранити в мене крашиться та вилітає гра'
2. Натисніть на '....'
3. Прогорніть '....'
4. Гляньте на помилку.

**Поведінка**
Я мав пройти поміж салюти а коли з'являється перший салют гра крашиться та вилітає , а проходити гру англійською чи рус. не цікаво.

**Знімки екрана**
Якщо можливо, додайте знімки екрана, щоб легше пояснити проблему.

**Комп'ютер (будь ласка, заповніть наступну інформацію):**
 - О.С: [Windows]
 - Браузер: [ Chrome]
 - Версія О.С: [Windows 11]
 - Версія перекладу: [v0.1.8]
 - Версія гри: [v1.10]

**Додатково**
Додайте сюди будь-який інший контекст проблеми.
ссилка на фото з помилкою [https://files.fm/u/953beuxqp#/view/hcxd4yq3y](url) якщо вона не працює її можна скопіювати та вставити в пошук у браузер

**Comment by ChulkyBow** [comment]
Вітання, sawer097.

Річ у тім, що ви грали лише в бета версію перекладу 2 розділу, чого ми не радимо робити, поки не опублікуємо його реліз.

Щодо крашу гри, то ми його вже виправили, і в наступній версії все працюватиме як належне.

Ми вже закінчили перекладати другий розділ, тому зараз перевіряємо його у грі, доробоюємо кілька дрібничок, і займаємося озвученням.

Гадаю, повна версія перекладу 2-го розділу буде вже в жовтні цього року.
