### ISSUE TITLE
[Помилка]

### ISSUE THREAD

**Issue by AlexUA2004** [yanchukcha/deltarune-ua#7]
Помилка перекладу під час розмови з Швом.
Коли Шов говорить на тему Світочів, замість "розлютившись" він каже "розлючившись".

Покрокове пояснення, як нам виявити помилку:
1. Перейдіть до крамниці Шова;
2. Виберіть і натисніть "теревені";
3. Виберіть і натисніть "світочі";
4. Розмовляємо до четвертої репліки, яка і містить помилку.

Знімок екрану
![Screenshot_20230227_214559](https://user-images.githubusercontent.com/124157335/221682001-4096e418-71ae-4fdd-8e1b-5d2820c426be.jpg)

Присутня як на комп'ютері, так і на Андроїд порті.
 Версія перекладу: 0.1.9

**Comment by yanchukcha** [comment]
Дякую, трохи наплутали — думали, що це синонім. Зараз зміню в тексті, виправлення буде серед інших у наступному релізі.
